### ISSUE TITLE
when sending failed. should configure the interval instead of trying to send again.

### ISSUE THREAD

**Issue by AkariDream** [Elytrium/LimboReconnect#11]
https://github.com/Elytrium/LimboQueue/issues/3
forgive my stupidity. i have too many windows open and dont pay attention to which plugin

**Comment by SkyWatcher2019** [comment]
Can you share the config.yml? Looks like misconfigured kick trigger message

**Comment by AkariDream** [comment]
![image](https://user-images.githubusercontent.com/71176602/220368254-ef042a59-f845-4d3c-ac46-f4c69a02cbef.png)
no. thats right. when a player is kicked out by viaversion because of a version difference when the server is not fully started. i dont want that to happen. because this will kick the player from Velocity

**Comment by AkariDream** [comment]
but since plugin thinks the server is already started. so try to send the player instantly. then move back to limbo. and so on and so forth.

**Comment by SkyWatcher2019** [comment]
Try to decrease check-interval to 1000-2000

**Comment by AkariDream** [comment]
![image](https://user-images.githubusercontent.com/71176602/220369318-2f9e4395-9036-4dee-956c-3d74886dfe26.png)
![image](https://user-images.githubusercontent.com/71176602/220369378-1c283582-d7d0-4e6a-9410-28f8f26d3322.png)
.

**Comment by AkariDream** [comment]
viaversion kicks out different versions of players when the server is not fully started. this is not a matter of checking the interval. check the motd text. or add an interval of attempts.

**Comment by SkyWatcher2019** [comment]
Hmm, looks like server responding to the ping before it fully started. Or Via loads after server started?

**Comment by SkyWatcher2019** [comment]
> instead of using pure tcpping to check server status.
wdym

**Comment by AkariDream** [comment]
all right. lets get a little bit clear:
i used viaversion. but though dont use it. the server will still kick different versions of the client. only when the server is fully started. via will accept different(but support) of the client.
motd respond only when the server is fully started. it is better than normal ping.

i tried to add limbo when the player was kick because of a different version. if the client is the same version as the server. the server dont kick.
open ports are after libraries are loaded. instead of opening when the server is fully started.

**Comment by SkyWatcher2019** [comment]
![image](https://user-images.githubusercontent.com/62600934/220371749-dafe7bda-4e62-4dc1-bf62-c625677ee6b5.png)
i don't think it's tcpping and server responds with it's version before full start.
I'll take a look at

**Comment by AkariDream** [comment]
> i don't think it's tcpping

things like tcpping. something that is not based on the minecraft protocol. i dont quite articulate it

**Comment by SkyWatcher2019** [comment]
> motd respond only when the server is fully started.

`this.server.ping().get(Config.IMP.PING_TIMEOUT, TimeUnit.MILLISECONDS)` -> `Component description`

**Comment by AkariDream** [comment]
> > motd respond only when the server is fully started.
> 
> `this.server.ping().get(Config.IMP.PING_TIMEOUT, TimeUnit.MILLISECONDS)` -> `Component description`
all right. my stupidity. 1.8 the server responds to motd anyway. ill find some other way to see how to make it work.

**Comment by SkyWatcher2019** [comment]
Can you show join-delay parameter from Via?

**Comment by AkariDream** [comment]
> Can you show join-delay parameter from Via?

wdym

**Comment by AkariDream** [comment]
idk what youre looking for. they're all here (most of the stuff is the default cfg. because i think its plug and use.
https://pastebin.com/L9Tm4HcC

**Comment by Akiranya** [comment]
> nvm, misunderstood hevav, gonna add this parameter to limboreconnect

thanks for the fix! just wanted to let you know that this also fixed https://github.com/KaspianDev/AntiPopup/issues
