### ISSUE TITLE
Time out when connecting with server that player can't join

### ISSUE THREAD

**Issue by AdamZG37** [Elytrium/LimboReconnect#16]
I have an issue.
When I try to join to the server that I am whitelisted I got disconnected. I tried to remove all plugins and only when this one was on the server the error repeated.

https://github.com/Elytrium/LimboReconnect/assets/130443171/59566e9b-7932-4516-b895-5067d537028e

**Comment by SkyWatcher2019** [comment]
LimboReconnect does nothing after sending players to their servers. Can you share server and proxy logs?

**Comment by AdamZG37** [comment]
Only when your plugin is installed the bug exist look.


https://github.com/Elytrium/LimboReconnect/assets/130443171/183c2d97-d0d4-4555-9fe4-0f983687bf05


https://github.com/Elytrium/LimboReconnect/assets/130443171/aef5211d-13b7-4e7d-80c8-08d6961c017d

**Comment by AdamZG37** [comment]
active devs :/

**Comment by L-udo** [comment]
![image](https://github.com/Elytrium/LimboReconnect/assets/18017425/77b4c6cd-b491-4331-9daf-e659cae6fd1f)
this occurs when the destination server is asleep,
