### ISSUE TITLE
Invalid regex in trigger-message will cause it to fail in a way hard to debug

### ISSUE THREAD

**Issue by whiler-sesame** [Elytrium/LimboReconnect#24]
An exception is thrown here, not printed, caught by me with java debugger
https://github.com/Elytrium/LimboReconnect/blob/6615aa9fd5997d30d4817b781c9b9e94c1aedd6c/src/main/java/net/elytrium/limboreconnect/listener/ReconnectListener.java#L58

This leads to ghost-like state, where player is not on backend and not in limbo, just waiting for time out.
Writing anything in chat in that state leads to issues like #21 #23.
I'm not an expert in Java, but I would suggest adding `try-catch` blocks there, kicking player on any errors.
Also, precompiling `Pattern` in advance while loading config can make this error more descriptive. Also javadoc says it can squish a bit of performance that way.

**Comment by whiler-sesame** [comment]
Also your maven repo is down for some reason, I can't PR a fix.
![image](https://github.com/Elytrium/LimboReconnect/assets/172549525/9ed98d32-fdeb-41a0-9f69-c344799288f8)

**Comment by hevav** [comment]
> Also your maven repo is down for some reason, I can't PR a fix. ![image](https://private-user-images.githubusercontent.com/172549525/340540195-9ed98d32-fdeb-41a0-9f69-c344799288f8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2OTI5OTUsIm5iZiI6MTcxODY5MjY5NSwicGF0aCI6Ii8xNzI1NDk1MjUvMzQwNTQwMTk1LTllZDk4ZDMyLWZkZWItNDFhMC05ZjY5LWMzNDQ3OTkyODhmOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxOFQwNjM4MTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02Y2I0MjM3Y2IyN2UyZDI5OTY4OWYwNTI0Zjc0ZGJkOGJmMTUxZThhOTc1YmFkYjczOTQzYTZjOTg0MDQ2YmQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.4xhU9t3i3JYrCXd7blVEtZNWC4Axeu1RBbzy1Hszui8)

try again

**Comment by SkyWatcher2019** [comment]
Oh, seriously... I never thought that issue was in regex.
