### ISSUE TITLE
Support 1.21/1.21.1

### ISSUE THREAD

**Issue by xDangles** [Elytrium/LimboReconnect#27]
No support for new clients, frequent connection errors after reboot on different client versions (forge/fabric/vanilla).

![изображение](https://github.com/user-attachments/assets/1d0a579c-c012-46f8-96ff-587c2c64b1ca)
[disconnect-2024-09-04_22.16.18-client.txt](https://github.com/user-attachments/files/16876382/disconnect-2024-09-04_22.16.18-client.txt)

**Comment by SkyWatcher2019** [comment]
Try [6a3e799](https://github.com/Elytrium/LimboReconnect/releases/tag/dev-build)
