### ISSUE TITLE
Failed to decode packet 'clientbound/minecraft:sound'

### ISSUE THREAD

**Issue by BluetoothWiFi** [Elytrium/LimboReconnect#29]
![image](https://github.com/user-attachments/assets/6d2d4b26-c297-4142-8871-ff36d31eee00)
![image](https://github.com/user-attachments/assets/0935a0e8-1429-4aca-8b86-961321ab8b29)
![image](https://github.com/user-attachments/assets/891322e9-8a3c-4dc8-928e-e799d726898b)

1. Server version: 1.21.1 - Purpur
2. Velocity version:  3.3.0-b436
3. Client versions, where get trouble: 1.21.1(vanilla/clean fabric), 1.21(vanilla/clean fabric/fabric with many mods), 1.20(vanilla/clean fabric), 1.20.4(vanilla)
P.S. Clean means fabric with out mods

**Comment by SkyWatcher2019** [comment]
Try [6a3e799](https://github.com/Elytrium/LimboReconnect/releases/tag/dev-build)

**Comment by BluetoothWiFi** [comment]
![image](https://github.com/user-attachments/assets/6e5ebd6f-c039-48ce-bdfe-ca0370ed754d)
Yes, thats work. Thank you for fast fix)
