### ISSUE TITLE
Packet play/100 (acq) was larger than I expected

### ISSUE THREAD

**Issue by Darwin1546** [Elytrium/LimboReconnect#33]
Error on server restart. Players a getting kicked

![изображение](https://github.com/user-attachments/assets/0fcb69e3-299f-43e2-b791-e09651cdd577)
`[Render thread/WARN]: Client disconnected with reason: Internal Exception: io.netty.handler.codec.DecoderException: java.io.IOException: Packet play/100 (acq) was larger than I expected, found 46 bytes extra whilst reading packet 100`

No additional errors in velocity console

LimboReconnect 1.1.7
Velocity 3.3.0-SNAPSHOT (git-f034c027-b426)
Minecraft 1.20.4

**Comment by legendofgow** [comment]
Same problem here

![Bez tytułu](https://github.com/user-attachments/assets/21306134-98b9-43bd-9bb5-46fcbd5964ea)

**Comment by UserNugget** [comment]
> Same problem here
> 
> ![Bez tytułu](https://private-user-images.githubusercontent.com/88216155/395729387-21306134-98b9-43bd-9bb5-46fcbd5964ea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQyMDE3NDUsIm5iZiI6MTczNDIwMTQ0NSwicGF0aCI6Ii84ODIxNjE1NS8zOTU3MjkzODctMjEzMDYxMzQtOThiOS00M2JkLTliYjUtNDZmY2JkNTk2NGVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE0VDE4MzcyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ2OWNmMjE5ZTU5NDhkMmJhYzllNDhiNjA2YTIzZjYzYjAzZDYyOTcwZDA1MjdiY2Q2M2MwNjFiMDk5ZDJmMTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.1-wY98W0ULcpjSgqqZNSd0GZRrxoFGhmu1Rsrlxyk3s)

It's not related to this issue, your issue is caused by ~~yet another~~ config-protocol-state race condition while this issue is caused by wrong packet id.
Please open other issue (and provide a way to reproduce it {:)
